# Generated by Django 3.2.4 on 2021-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=265, verbose_name='Tên Sản Phẩm')),
                ('gia_goc', models.CharField(max_length=50, verbose_name='Giá gốc')),
                ('gia_sale', models.CharField(max_length=50, verbose_name='Giá sale')),
                ('sale_rate', models.CharField(max_length=10, verbose_name='Phần trăm sale')),
                ('con_hang', models.CharField(max_length=100, null=True, verbose_name='Còn hàng')),
                ('luot_danh_gia', models.CharField(default=0, max_length=100, verbose_name='Số đánh giá')),
                ('sao', models.CharField(default=0, max_length=100, verbose_name='Số sao')),
                ('link_sp', models.URLField(max_length=100, null=True, verbose_name='Link sản phẩm')),
            ],
        ),
    ]
