# Generated by Django 3.2.5 on 2021-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gia_goc',
            field=models.FloatField(default=0, verbose_name='Giá gốc'),
        ),
        migrations.AlterField(
            model_name='info',
            name='gia_sale',
            field=models.FloatField(default=0, verbose_name='Giá sale'),
        ),
        migrations.AlterField(
            model_name='info',
            name='link_sp',
            field=models.URLField(max_length=265, null=True, verbose_name='Link sản phẩm'),
        ),
        migrations.AlterField(
            model_name='info',
            name='luot_danh_gia',
            field=models.IntegerField(default=0, verbose_name='Số đánh giá'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sao',
            field=models.IntegerField(default=0, verbose_name='Số sao'),
        ),
        migrations.AlterField(
            model_name='info',
            name='ten',
            field=models.CharField(max_length=265, verbose_name='Tên sản phẩm'),
        ),
    ]
