# Generated by Django 3.2.5 on 2021-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_auto_20210803_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='anh_sp',
            field=models.ImageField(blank=True, upload_to='media_anh', verbose_name='Ảnh sản phẩm'),
        ),
    ]
